export BLOCK_X=16
export BLOCK_Y=8
export BLOCK_Z=8
export NGPUS=1
export ITERATIONS=64
export DIM=256
export STENCIL_DEPTH=1
#export HALO_DEPTH=1 # Needs to be a multiplum of 2 and lower than ITERATIONS
export DEBUG=true
export SMEM=false
export COOP=true
export REPEAT=20
export YME_WORKING_FOLDER=thesis
