export BLOCK_X=32
export BLOCK_Y=8
export BLOCK_Z=4
export NGPUS=1
export ITERATIONS=8
export DIM=1024
export STENCIL_DEPTH=64
#export HALO_DEPTH=1 # Needs to be a multiplum of 2 and lower than ITERATIONS
export DEBUG=false
export SMEM=false
export COOP=false
export REPEAT=20
export YME_WORKING_FOLDER=thesis
export UNROLL_X=2
